### ISSUE TITLE
Update example link 

### ISSUE THREAD

**Issue by ShankyTiwari** [ShankyTiwari/mat-list-touch#11]
Create and deploy a new demo with latest version.

**Comment by davidzwa** [comment]
Would be very nice! I updated the component's demo in the upcoming v2.1 app-module.

**Comment by ShankyTiwari** [comment]
Due to limited resources, I don't have deployed the demo on Server/Firebase yet. But  I have deployed it on Stackblitz. In the next couple of days, I'll get my Laptop and I will deploy it on a Server.

**Comment by ShankyTiwari** [comment]
The Demo repository is [here](https://github.com/ShankyTiwari/mat-list-touch-example).
