### ISSUE TITLE
swipe to see stock buttons

### ISSUE THREAD

**Issue by GlauberF** [ShankyTiwari/mat-list-touch#6]
In the examples, you swipe to delete an item, but would like to know if there is a way for me to slide my finger and appear more than one button, which performs more than one action.

If not, would you know any libraries for this?

**Comment by davidzwa** [comment]
I got an update, still need to PR and test it. If I dont get to it in a week, mention me.

**Comment by GlauberF** [comment]
Perfect @davidzwa 
I'm working on a project that needs it and I'm stuck because I'm looking for something.
Not wanting to speed up, but when I can send I am grateful.

**Comment by davidzwa** [comment]
Sorry, had exams. Will get to it before Sunday. It is based on the following fork:
[Fork github](https://github.com/davidzwa/mat-list-touch?organization=davidzwa&organization=davidzwa)

It is not finished, but if youre really stuck, I'd advise you to take a look.

**Comment by davidzwa** [comment]
@GlauberF still interested? I've got a finished version these days, but it might be undermaintained.
So would be best if you directly include the module yourself and develop from there.

It's quite a nice thing now!

**Comment by GlauberF** [comment]
Yes, what is the repository link?
do you have a demo?

**Comment by davidzwa** [comment]
Will work on that once I get back home!

**Comment by davidzwa** [comment]
![image](https://user-images.githubusercontent.com/6005355/70910861-e8788700-2010-11ea-924f-a37767b83ea7.png)
This is how I made it look. 2 different actions on both side and coloring can be changed.

Im not totally satisfied with the callback-way of implementing, but it's what I understand.

**Comment by GlauberF** [comment]
interesting, when you have the demo or repository link send me.

**Comment by davidzwa** [comment]
I pushed some code to v2.0-mat-list-touch branch.

Check it out, it is not working, something I will improve on later.

**Comment by davidzwa** [comment]
@GlauberF please bump me. Currently only doing this to help you (please look at #5).

**Comment by maddy2894** [comment]
Hey guys, @davidzwa any updates on the stock buttons?

**Comment by davidzwa** [comment]
Will look at it tonight to see what updates I've got in my project. Do clone the v2 branch if you want to see it in action (branch https://github.com/ShankyTiwari/ng-swipe-to-delete/tree/feature/v2.0-mat-list-touch).

**Comment by davidzwa** [comment]
Working on the update for ng9/ng10 and a minimal working example to fit.

**Comment by davidzwa** [comment]
@maddy2894 it's finally here! #8

**Comment by maddy2894** [comment]
Cool. Will look into it. 

Thank you

**Comment by davidzwa** [comment]
The module has been updated! Glad to say this can be closed 🎉
